// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_skins_2 = "CgkIz4GOyIwQEAIQEA"; // <GPGSID>
        public const string achievement_skins_1 = "CgkIz4GOyIwQEAIQDw"; // <GPGSID>
        public const string achievement_distance_1 = "CgkIz4GOyIwQEAIQBQ"; // <GPGSID>
        public const string achievement_credits_4 = "CgkIz4GOyIwQEAIQDQ"; // <GPGSID>
        public const string achievement_credits_5 = "CgkIz4GOyIwQEAIQDg"; // <GPGSID>
        public const string achievement_credits_2 = "CgkIz4GOyIwQEAIQCw"; // <GPGSID>
        public const string achievement_credits_3 = "CgkIz4GOyIwQEAIQDA"; // <GPGSID>
        public const string achievement_credits_1 = "CgkIz4GOyIwQEAIQCg"; // <GPGSID>
        public const string achievement_distance_2 = "CgkIz4GOyIwQEAIQBg"; // <GPGSID>
        public const string achievement_distance_4 = "CgkIz4GOyIwQEAIQCA"; // <GPGSID>
        public const string achievement_boost = "CgkIz4GOyIwQEAIQBA"; // <GPGSID>
        public const string achievement_skins_4 = "CgkIz4GOyIwQEAIQEg"; // <GPGSID>
        public const string achievement_skins_5 = "CgkIz4GOyIwQEAIQEw"; // <GPGSID>
        public const string achievement_distance_5 = "CgkIz4GOyIwQEAIQCQ"; // <GPGSID>
        public const string achievement_distance_3 = "CgkIz4GOyIwQEAIQBw"; // <GPGSID>
        public const string achievement_informed = "CgkIz4GOyIwQEAIQAQ"; // <GPGSID>
        public const string leaderboard_altitude = "CgkIz4GOyIwQEAIQAg"; // <GPGSID>
        public const string achievement_skins_3 = "CgkIz4GOyIwQEAIQEQ"; // <GPGSID>

}

